### ISSUE TITLE
更新之后无法使用hexo命令

### ISSUE THREAD

**Issue by RainVector** [MOxFIVE/hexo-theme-yelee#112]
1. 进入`themes/yelee/`文件夹下使用更新命令`git pull git@github.com:MOxFIVE/hexo-theme-yelee.git`
2. 然后回到主文件加下，使用命令`hexo s`等命令出错
`
FATAL Cannot read property 'code' of undefined
TypeError: Cannot read property 'code' of undefined
    at C:\Users\RainVector\AppData\Roaming\npm\node_modules\hexo-cli\lib\find_pkg.js:23:25
    at tryCatcher (C:\Users\RainVector\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\RainVector\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promise.js:503:31)
    at Promise._settlePromise (C:\Users\RainVector\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promise.js:560:18)
    at Promise._settlePromise0 (C:\Users\RainVector\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promise.js:605:10)
    at Promise._settlePromises (C:\Users\RainVector\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promise.js:680:18)
    at Async._drainQueue (C:\Users\RainVector\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\async.js:126:16)
    at Async._drainQueues (C:\Users\RainVector\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\RainVector\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
`

**Comment by RainVector** [comment]
我已经解决了。
问题是merge冲突；
解决方法：`git --reset merge`
